formulaire 1. tuto écrit + code complet
get-focus/deprecated-focus-tuto-v3 pull request #5
Opened 2017-02-10 12:12 UTC by GtAntoine

Petites modifications des fichiers package.json et src/application.js à reporter sur la branche tutorial.

2017-02-13 12:46 UTC, TomGallon requested changes

2017-02-13 12:46 UTC, TomGallon commented on src/views/user/card.js
> +const Card = ({title,description, route, destination }) => {
why don't you use the Panel component ?

https://github.com/get-focus/focus-components/tree/develop/src/panel

2017-02-13 12:46 UTC, TomGallon commented on src/views/user/card.js
> +const Card = ({title,description, route, destination }) => {
if it is useless, please remove this component.

2017-02-13 17:13 UTC, Ephrame reviewed
Can you put some comments to explain the line in the code directly ?

2017-02-13 17:13 UTC, Ephrame commented on src/services/index.js
> +export const loadUser = async ({id}) => {
For the loadUser you have to create a webService specific, like this, the "then" is not necessary

2017-02-13 17:13 UTC, Ephrame commented on src/views/user/user-form.js
> +const ConnectedUserForm = compose(
When there is just one 'metadata' it's not necessary to declare it in each fieldFor

2017-02-17 08:47 UTC, Ephrame commented
There is no changement about the service ?

2017-02-17 08:56 UTC, Ephrame commented on src/views/user/user-form.js
> +        {fieldFor('uuid', {entityPath: 'user'})}
Why do you keep the entityPath ?

2017-02-21 13:12 UTC, TomGallon requested changes

2017-02-21 13:12 UTC, TomGallon commented on src/services/index.js
> +};
Please remove the then. It is useless.

2017-02-21 13:35 UTC, GtAntoine commented on src/services/index.js
> +export const loadUser = async ({id}) => {
Not sure how to write it without the then

2017-02-22 17:30 UTC, merged