formulaire 2 tuto + code complet
get-focus/deprecated-focus-tuto-v3 pull request #6
Opened 2017-02-10 15:12 UTC by GtAntoine

2017-02-13 12:48 UTC, TomGallon requested changes

2017-02-13 12:48 UTC, TomGallon commented on src/views/user/card.js
> +const Card = ({title,description, route, destination }) => {
Please remove this component.

2017-02-17 08:52 UTC, Ephrame commented on src/config/translations/fr-FR.js
> +    },
it's a good i18n key, you have to indicate the name of the form. It's specific to one form.

2017-02-17 08:52 UTC, Ephrame commented on src/services/index.js
> +}
You have to make a specific webService

2017-02-17 08:52 UTC, Ephrame commented on src/views/02-Les listes/README.md
> +    return { ...data.user, __Focus__updateRequestStatus: data.__Focus__updateRequestStatus };
You want data.finance and not user

2017-02-17 08:52 UTC, Ephrame commented on src/views/02-Les listes/README.md
> +    await new Promise((resolve, reject) => {
it's finance not user

2017-02-17 08:52 UTC, Ephrame commented on src/views/02-Les listes/README.md
> +...et d'importer la vu dans le router !
vue

2017-02-17 08:57 UTC, Ephrame commented on src/views/02-Les listes/README.md
> +        {fieldFor('name', {entityPath: 'finance'})}
The entityPath is not necessary

2017-02-21 13:43 UTC, TomGallon requested changes

2017-02-21 13:43 UTC, TomGallon commented on src/views/02-Les listes/README.md
> +            ...data.finance,
please remove the THEN.

2017-02-21 13:43 UTC, TomGallon commented on src/views/home.js
> +        <div style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'center'}}>
Could you please avoid to use style property ?
We recommand to declare CSS in project instead.

2017-02-21 13:43 UTC, GtAntoine commented on src/config/translations/fr-FR.js
> +    },
This remark is not clear for me

2017-02-23 13:52 UTC, merged