formulaire 3 tuto + code complet
get-focus/deprecated-focus-tuto-v3 pull request #7
Opened 2017-02-13 09:19 UTC by GtAntoine

note : attention au problèmes si les domaines et les entity-definitions ne correspondent pas à ce que renvoie l'api.

2017-02-17 08:55 UTC, Ephrame commented on src/reducer/user-finance-reducer.js
> +
Why do you create some variable to put them in the same object ?

2017-02-21 13:55 UTC, TomGallon requested changes

2017-02-21 13:55 UTC, TomGallon commented on api/index.js
> +        sex: 'unknown'
Could you please change sex value by null value (or undefined)

2017-02-21 13:55 UTC, TomGallon commented on src/services/index.js
> +        return {
please remove the THEN

2017-02-21 13:55 UTC, TomGallon commented on src/views/03-Deux noeuds/README.md
> +        return {
remove the THEN

2017-02-23 14:26 UTC, merged