formulaire 4 tuto + code complet
get-focus/deprecated-focus-tuto-v3 pull request #8
Opened 2017-02-13 17:16 UTC by GtAntoine

2017-02-17 09:01 UTC, Ephrame reviewed
There is no tuto ?

2017-02-17 09:01 UTC, Ephrame commented on src/services/index.js
> +    return {...data, __Focus__updateRequestStatus: data.__Focus__updateRequestStatus};
you can return data diectly

2017-02-17 09:01 UTC, Ephrame commented on src/views/user/custom-finance-user-form.js
> +
The ScrollSpyContainer is not necessary, it was just a test. Can you remove it ? No ? What do you think ?

2017-02-17 09:01 UTC, Ephrame commented on src/views/user/custom-finance-user-form.js
> +    <Panel title='Finance' {...otherProps}>
The entityPath is not necessary

2017-02-17 10:17 UTC, GtAntoine commented on src/views/user/custom-finance-user-form.js
> +
I thought it was a good idea to let it as an exemple. I'd prefer to add a paragraph about it in the tutorial than remove it.

2017-02-21 13:54 UTC, TomGallon requested changes

2017-02-21 13:54 UTC, TomGallon commented on src/services/index.js
> +        return {
remove the THEN

2017-02-21 13:54 UTC, TomGallon commented on src/views/user/custom-finance-user-form.js
> +
Ok, we keep it. Please add a sentence about it.

2017-02-23 15:28 UTC, merged